[codestyle]
lang="python"
workspace_dir="/Users/kzy/src/github.com/kazuya0202/atcoder"
template_file="/Users/kzy/src/github.com/kazuya0202/atcoder/_template.py"

[etc]
in_example_format="test/sample-{}.in"
out_example_format="test/sample-{}.out"

[submit]
submit_filename="main.py"
